# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 0);
user_pref("b2g.wifi.allow_unsafe_wpa_eap", true);
user_pref("browser.homescreenURL", "app://system.gaiamobile.org/index.html");
user_pref("browser.manifestURL", "app://system.gaiamobile.org/manifest.webapp");
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("dom.mms.requestStatusReport", false);
user_pref("dom.mms.retrieval_mode", "automatic-home");
user_pref("dom.mms.version", 17);
user_pref("dom.mozApps.used", true);
user_pref("dom.sms.requestStatusReport", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.lastAppVersion", "28.0");
user_pref("extensions.lastPlatformVersion", "28.0");
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140331164005");
user_pref("gecko.mstone", "28.0");
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.offmainthreadcomposition.log-animations", false);
user_pref("layout.css.dpi", 227);
user_pref("layout.css.sticky.enabled", true);
user_pref("marionette.contentListener", false);
user_pref("network.dns.localDomains", "gaiamobile.org,bluetooth.gaiamobile.org,browser.gaiamobile.org,calendar.gaiamobile.org,camera.gaiamobile.org,clock.gaiamobile.org,communications.gaiamobile.org,costcontrol.gaiamobile.org,email.gaiamobile.org,fl.gaiamobile.org,fm.gaiamobile.org,gallery.gaiamobile.org,homescreen.gaiamobile.org,keyboard.gaiamobile.org,music.gaiamobile.org,pdfjs.gaiamobile.org,ringtones.gaiamobile.org,setringtone.gaiamobile.org,settings.gaiamobile.org,sms.gaiamobile.org,system.gaiamobile.org,video.gaiamobile.org,wallpaper.gaiamobile.org,wappush.gaiamobile.org,marketplace-dev.allizom.org.gaiamobile.org,marketplace.allizom.org.gaiamobile.org,mochitest.gaiamobile.org,marketplace.firefox.com.gaiamobile.org,tvmarketplace.gaiamobile.org,wikipedia.gaiamobile.org,twittershare.gaiamobile.org,ds-test.gaiamobile.org,demo-keyboard.gaiamobile.org,geoloc.gaiamobile.org,membuster.gaiamobile.org,music2.gaiamobile.org,test-ime.gaiamobile.org,share-receiver.gaiamobile.org,template.gaiamobile.org,test-agent.gaiamobile.org,test-container.gaiamobile.org,test-keyboard-app.gaiamobile.org,test-otasp.gaiamobile.org,test-receiver-1.gaiamobile.org,test-receiver-2.gaiamobile.org,test-receiver-inline.gaiamobile.org,test-wappush.gaiamobile.org,uitest.gaiamobile.org");
user_pref("network.http.max-connections-per-server", 15);
user_pref("privacy.donottrackheader.value", -1);
user_pref("ril.debugging.enabled", false);
user_pref("ril.mms.mmsc", "");
user_pref("ril.mms.mmsport", 0);
user_pref("ril.mms.mmsproxy", "");
user_pref("ril.radio.disabled", false);
user_pref("toolkit.telemetry.previousBuildID", "20140331164005");
